"""initial schema

Revision ID: 04b51c348061
Revises: 
Create Date: 2026-08-29 20:57:35.846312
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.db  # noqa: F401  (custom column types referenced below)

revision: str = '04b51c348061'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_role_active', ['role', 'is_active'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payment_reference', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('received_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_webhook_events_payment_reference'), ['payment_reference'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('raised_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('minimum_contribution', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contributor_count', sa.Integer(), nullable=False),
    sa.Column('deadline', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('governance_status', sa.String(length=20), nullable=False),
    sa.Column('governance_closes_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('qr_token', sa.String(length=64), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_category'), ['category'], unique=False)
        batch_op.create_index('ix_campaigns_category_status', ['category', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index('ix_campaigns_deadline', ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaigns_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)
        batch_op.create_index('ix_campaigns_status_approval', ['status', 'approval_status'], unique=False)

    op.create_table('kyc_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('verification_reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('verified_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_reference')
    )
    with op.batch_alter_table('kyc_verifications', schema=None) as batch_op:
        batch_op.create_index('ix_kyc_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feasibility_score', sa.Integer(), nullable=True),
    sa.Column('problem_clarity_score', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('concerns', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('questions_for_creator', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_ai_analysis_campaign_type', ['campaign_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_created_at'), ['created_at'], unique=False)

    op.create_table('ai_community_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('positive_percentage', sa.Float(), nullable=False),
    sa.Column('neutral_percentage', sa.Float(), nullable=False),
    sa.Column('negative_percentage', sa.Float(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('top_concerns', sa.JSON(), nullable=True),
    sa.Column('positive_themes', sa.JSON(), nullable=True),
    sa.Column('aspect_distribution', sa.JSON(), nullable=True),
    sa.Column('community_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('questions_from_community', sa.JSON(), nullable=True),
    sa.Column('risk_change', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_community_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_community_insights_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_community_insights_created_at'), ['created_at'], unique=False)

    op.create_table('campaign_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('application_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=80), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    with op.batch_alter_table('campaign_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_applications_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_applications_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_applications_status'), ['status'], unique=False)

    op.create_table('campaign_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_documents_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_events_event_type'), ['event_type'], unique=False)

    op.create_table('campaign_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('outcome_type', sa.String(length=30), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voting_weight_mode', sa.String(length=30), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('selected_outcome', sa.String(length=30), nullable=True),
    sa.Column('executed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('locked_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('aspect', sa.String(length=30), nullable=True),
    sa.Column('aspects', sa.JSON(), nullable=True),
    sa.Column('sentiment_model', sa.String(length=80), nullable=True),
    sa.Column('analyzed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contributor_id', name='uq_feedback_campaign_user')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_aspect'), ['aspect'], unique=False)
        batch_op.create_index('ix_feedback_campaign_created', ['campaign_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_contributor_id'), ['contributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_sentiment'), ['sentiment'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=80), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=80), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('webhook_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_type'), ['payment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_order_id'), ['razorpay_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_payment_id'), ['razorpay_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index('ix_payments_type_status', ['payment_type', 'status'], unique=False)
        batch_op.create_index('ix_payments_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('governance_round', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('blockchain_tx', sa.String(length=80), nullable=True),
    sa.Column('blockchain_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contributor_id', 'governance_round', name='uq_vote_once_per_round')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('ix_votes_campaign_choice', ['campaign_id', 'choice'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_contributor_id'), ['contributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_created_at'), ['created_at'], unique=False)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('blockchain_tx', sa.String(length=80), nullable=True),
    sa.Column('blockchain_record_id', sa.Integer(), nullable=True),
    sa.Column('blockchain_attempts', sa.Integer(), nullable=False),
    sa.Column('blockchain_error', sa.String(length=500), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_record_id'], ['blockchain_transactions.id'], name='fk_contribution_blockchain_record', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id'),
    sa.UniqueConstraint('payment_id', name='uq_contribution_payment')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index('ix_contributions_campaign_created', ['campaign_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_contributions_contributor_created', ['contributor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_contributor_id'), ['contributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_status'), ['status'], unique=False)

    op.create_table('blockchain_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('vote_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=False),
    sa.Column('network', sa.String(length=40), nullable=False),
    sa.Column('contract_address', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_contribution_id'), ['contribution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_tx_hash'), ['tx_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_blockchain_transactions_vote_id'), ['vote_id'], unique=False)
        batch_op.create_index('ix_chain_campaign_type', ['campaign_id', 'record_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blockchain_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_chain_campaign_type')
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_vote_id'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_record_type'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_contribution_id'))
        batch_op.drop_index(batch_op.f('ix_blockchain_transactions_campaign_id'))

    op.drop_table('blockchain_transactions')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_status'))
        batch_op.drop_index(batch_op.f('ix_contributions_created_at'))
        batch_op.drop_index(batch_op.f('ix_contributions_contributor_id'))
        batch_op.drop_index('ix_contributions_contributor_created')
        batch_op.drop_index(batch_op.f('ix_contributions_campaign_id'))
        batch_op.drop_index('ix_contributions_campaign_created')

    op.drop_table('contributions')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_created_at'))
        batch_op.drop_index(batch_op.f('ix_votes_contributor_id'))
        batch_op.drop_index(batch_op.f('ix_votes_campaign_id'))
        batch_op.drop_index('ix_votes_campaign_choice')

    op.drop_table('votes')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index('ix_payments_user_created')
        batch_op.drop_index('ix_payments_type_status')
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_type'))
        batch_op.drop_index(batch_op.f('ix_payments_campaign_id'))

    op.drop_table('payments')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_sentiment'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_contributor_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_campaign_id'))
        batch_op.drop_index('ix_feedback_campaign_created')
        batch_op.drop_index(batch_op.f('ix_feedback_aspect'))

    op.drop_table('feedback')
    op.drop_table('campaign_outcomes')
    with op.batch_alter_table('campaign_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_campaign_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_events_campaign_id'))

    op.drop_table('campaign_events')
    with op.batch_alter_table('campaign_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_documents_campaign_id'))

    op.drop_table('campaign_documents')
    with op.batch_alter_table('campaign_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_applications_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_applications_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_applications_creator_id'))

    op.drop_table('campaign_applications')
    with op.batch_alter_table('ai_community_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_community_insights_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_community_insights_campaign_id'))

    op.drop_table('ai_community_insights')
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_created_at'))
        batch_op.drop_index('ix_ai_analysis_campaign_type')
        batch_op.drop_index(batch_op.f('ix_ai_analysis_campaign_id'))

    op.drop_table('ai_analysis')
    with op.batch_alter_table('kyc_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_verifications_user_id'))
        batch_op.drop_index('ix_kyc_user_status')

    op.drop_table('kyc_verifications')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_status_approval')
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_slug'))
        batch_op.drop_index(batch_op.f('ix_campaigns_public_id'))
        batch_op.drop_index('ix_campaigns_deadline')
        batch_op.drop_index(batch_op.f('ix_campaigns_creator_id'))
        batch_op.drop_index('ix_campaigns_category_status')
        batch_op.drop_index(batch_op.f('ix_campaigns_category'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_active')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
