"""Domain enumerations shared by models, schemas and services.

These are stored as strings in the database (portable across Postgres and the
SQLite dev fallback, and safe to extend without a type migration).
"""

from __future__ import annotations

from enum import StrEnum


class UserRole(StrEnum):
    CREATOR = "CREATOR"
    CONTRIBUTOR = "CONTRIBUTOR"
    ADMIN = "ADMIN"


class KYCStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    SUBMITTED = "SUBMITTED"
    PROCESSING = "PROCESSING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class CampaignStatus(StrEnum):
    DRAFT = "DRAFT"
    KYC_PENDING = "KYC_PENDING"
    FEE_PENDING = "FEE_PENDING"
    ANALYSIS_PENDING = "ANALYSIS_PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    LIVE = "LIVE"
    COMPLETED = "COMPLETED"
    TARGET_MET = "TARGET_MET"
    TARGET_MISSED = "TARGET_MISSED"
    GOVERNANCE = "GOVERNANCE"
    REFUND_PENDING = "REFUND_PENDING"
    CONTINUED = "CONTINUED"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"


PUBLIC_CAMPAIGN_STATUSES = {
    CampaignStatus.LIVE,
    CampaignStatus.COMPLETED,
    CampaignStatus.TARGET_MET,
    CampaignStatus.TARGET_MISSED,
    CampaignStatus.GOVERNANCE,
    CampaignStatus.REFUND_PENDING,
    CampaignStatus.CONTINUED,
    CampaignStatus.CLOSED,
}

FUNDABLE_CAMPAIGN_STATUSES = {CampaignStatus.LIVE, CampaignStatus.CONTINUED}


class ApprovalStatus(StrEnum):
    NOT_SUBMITTED = "NOT_SUBMITTED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class ApplicationStatus(StrEnum):
    DRAFT = "DRAFT"
    FEE_PENDING = "FEE_PENDING"
    FEE_PAID = "FEE_PAID"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class PaymentType(StrEnum):
    APPLICATION_FEE = "APPLICATION_FEE"
    CONTRIBUTION = "CONTRIBUTION"


class PaymentStatus(StrEnum):
    CREATED = "CREATED"
    PENDING = "PENDING"
    CAPTURED = "CAPTURED"
    FAILED = "FAILED"
    REFUND_INITIATED = "REFUND_INITIATED"
    REFUNDED = "REFUNDED"


class ContributionStatus(StrEnum):
    """Contribution lifecycle.

    Payment verification and blockchain anchoring are deliberately separate: a
    chain outage can never move a contribution out of a verified money state.
    """

    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    BLOCKCHAIN_PENDING = "BLOCKCHAIN_PENDING"
    BLOCKCHAIN_RECORDED = "BLOCKCHAIN_RECORDED"
    BLOCKCHAIN_FAILED = "BLOCKCHAIN_FAILED"
    REFUND_PENDING = "REFUND_PENDING"
    REFUNDED = "REFUNDED"


class Sentiment(StrEnum):
    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    NEGATIVE = "NEGATIVE"
    PENDING = "PENDING"
    FAILED = "FAILED"


class FeedbackAspect(StrEnum):
    FUNDING_TARGET = "FUNDING_TARGET"
    EXECUTION_PLAN = "EXECUTION_PLAN"
    TEAM = "TEAM"
    SCALABILITY = "SCALABILITY"
    PRODUCT = "PRODUCT"
    IMPACT = "IMPACT"
    PRICING = "PRICING"
    TECHNOLOGY = "TECHNOLOGY"
    TRUST = "TRUST"
    OTHER = "OTHER"


ASPECT_LABELS: dict[str, str] = {
    FeedbackAspect.FUNDING_TARGET: "Funding Target",
    FeedbackAspect.EXECUTION_PLAN: "Execution Plan",
    FeedbackAspect.TEAM: "Team Experience",
    FeedbackAspect.SCALABILITY: "Scalability",
    FeedbackAspect.PRODUCT: "Product Quality",
    FeedbackAspect.IMPACT: "Social Impact",
    FeedbackAspect.PRICING: "Pricing",
    FeedbackAspect.TECHNOLOGY: "Technology",
    FeedbackAspect.TRUST: "Trust",
    FeedbackAspect.OTHER: "Other",
}


class AnalysisType(StrEnum):
    CAMPAIGN = "CAMPAIGN"
    COMMUNITY = "COMMUNITY"


class AnalysisStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    DEGRADED = "DEGRADED"  # fallback used because the model was unavailable
    FAILED = "FAILED"


class VoteChoice(StrEnum):
    REFUND = "REFUND"
    CONTINUE = "CONTINUE"


class OutcomeType(StrEnum):
    """What a campaign has predefined should happen if the target is missed."""

    CONTRIBUTOR_VOTE = "CONTRIBUTOR_VOTE"
    AUTOMATIC_REFUND = "AUTOMATIC_REFUND"
    KEEP_WHAT_YOU_RAISE = "KEEP_WHAT_YOU_RAISE"


class GovernanceStatus(StrEnum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class VotingWeightMode(StrEnum):
    ONE_PERSON_ONE_VOTE = "ONE_PERSON_ONE_VOTE"
    CONTRIBUTION_WEIGHTED = "CONTRIBUTION_WEIGHTED"


class BlockchainTxStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"


class BlockchainRecordType(StrEnum):
    CAMPAIGN_REGISTERED = "CAMPAIGN_REGISTERED"
    CONTRIBUTION = "CONTRIBUTION"
    VOTING_OPENED = "VOTING_OPENED"
    VOTE = "VOTE"
    VOTING_CLOSED = "VOTING_CLOSED"
    OUTCOME = "OUTCOME"


class EventType(StrEnum):
    """Campaign timeline + platform audit action names."""

    CREATOR_REGISTERED = "CREATOR_REGISTERED"
    CONTRIBUTOR_REGISTERED = "CONTRIBUTOR_REGISTERED"
    USER_LOGGED_IN = "USER_LOGGED_IN"
    KYC_SUBMITTED = "KYC_SUBMITTED"
    KYC_VERIFIED = "KYC_VERIFIED"
    KYC_REJECTED = "KYC_REJECTED"
    APPLICATION_FEE_ORDER_CREATED = "APPLICATION_FEE_ORDER_CREATED"
    APPLICATION_FEE_PAID = "APPLICATION_FEE_PAID"
    CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
    CAMPAIGN_UPDATED = "CAMPAIGN_UPDATED"
    CAMPAIGN_SUBMITTED = "CAMPAIGN_SUBMITTED"
    AI_ANALYSIS_STARTED = "AI_ANALYSIS_STARTED"
    AI_ANALYSIS_COMPLETED = "AI_ANALYSIS_COMPLETED"
    AI_ANALYSIS_FAILED = "AI_ANALYSIS_FAILED"
    CAMPAIGN_APPROVED = "CAMPAIGN_APPROVED"
    CAMPAIGN_REJECTED = "CAMPAIGN_REJECTED"
    CAMPAIGN_CHANGES_REQUESTED = "CAMPAIGN_CHANGES_REQUESTED"
    CAMPAIGN_PUBLISHED = "CAMPAIGN_PUBLISHED"
    QR_GENERATED = "QR_GENERATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    CONTRIBUTION_ORDER_CREATED = "CONTRIBUTION_ORDER_CREATED"
    CONTRIBUTION_PAYMENT_VERIFIED = "CONTRIBUTION_PAYMENT_VERIFIED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_DUPLICATE_IGNORED = "WEBHOOK_DUPLICATE_IGNORED"
    BLOCKCHAIN_CONTRIBUTION_RECORDED = "BLOCKCHAIN_CONTRIBUTION_RECORDED"
    BLOCKCHAIN_RECORD_FAILED = "BLOCKCHAIN_RECORD_FAILED"
    BLOCKCHAIN_RETRY_TRIGGERED = "BLOCKCHAIN_RETRY_TRIGGERED"
    FEEDBACK_CREATED = "FEEDBACK_CREATED"
    SENTIMENT_ANALYZED = "SENTIMENT_ANALYZED"
    COMMUNITY_INSIGHTS_GENERATED = "COMMUNITY_INSIGHTS_GENERATED"
    CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED"
    TARGET_MET = "TARGET_MET"
    TARGET_MISSED = "TARGET_MISSED"
    VOTING_OPENED = "VOTING_OPENED"
    VOTE_CAST = "VOTE_CAST"
    VOTING_CLOSED = "VOTING_CLOSED"
    OUTCOME_SELECTED = "OUTCOME_SELECTED"
    REFUND_REQUESTED = "REFUND_REQUESTED"
    REFUND_COMPLETED = "REFUND_COMPLETED"
    CAMPAIGN_CONTINUED = "CAMPAIGN_CONTINUED"
    CAMPAIGN_CLOSED = "CAMPAIGN_CLOSED"
    DEMO_CONTROL_USED = "DEMO_CONTROL_USED"


class CampaignCategory(StrEnum):
    TECHNOLOGY = "TECHNOLOGY"
    ENVIRONMENT = "ENVIRONMENT"
    HEALTHCARE = "HEALTHCARE"
    EDUCATION = "EDUCATION"
    AGRICULTURE = "AGRICULTURE"
    SOCIAL_IMPACT = "SOCIAL_IMPACT"
    ENERGY = "ENERGY"
    ARTS = "ARTS"
    OTHER = "OTHER"
